import {articlePath,minutes,text,html,route,safeUrl,publicNodes,postImage} from '../lib/content.mjs';
import {Share} from './Controls';
export function Empty({title='More stories are on their way.',children}) {return <div className="empty"><h2>{title}</h2><p>{children||'Explore the latest from the journal while we prepare this collection.'}</p><a className="text-link" href="/journal/">Browse the journal ↗</a></div>;}
export function Picture({image,priority=false,className=''}) {return safeUrl(image?.sourceUrl)?<img className={className} src={safeUrl(image.sourceUrl)} alt={image.altText||''} width={image.mediaDetails?.width||960} height={image.mediaDetails?.height||640} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':undefined}/>:<span className={'image-placeholder '+className} aria-hidden="true"><svg viewBox="0 0 40 40"><path d="M20 2v36M2 20h36M7 7l26 26M7 33 26 7" stroke="currentColor" strokeWidth="2"/></svg></span>;}
export function Category({post}) {const term=[...(post.categories?.nodes||[])].sort((a,b)=>a.slug.localeCompare(b.slug))[0];return term?<a className="eyebrow accent" href={'/category/'+term.slug+'/'}>{text(term.name)}</a>:<span className="eyebrow accent">The journal</span>;}
export function Byline({post}){const author=post.author?.node;return <div className="meta">{author&&<a href={'/authors/'+author.slug+'/'}>{text(author.name)}</a>}<span>·</span><span>{minutes(post)}</span></div>;}
export function Card({post}){return <article className="card"><a className="image-link" href={articlePath(post)}><Picture image={postImage(post)}/></a><Category post={post}/><h3><a href={articlePath(post)}>{text(post.title)}</a></h3><Byline post={post}/></article>;}
export function Cards({posts}){return posts.length?<div className="cards archive-grid">{posts.map(post=><Card key={post.databaseId} post={post}/>)}</div>:<Empty/>;}
export function Pagination({connection,base,query={}}){if(!connection?.pageInfo?.hasNextPage)return null;const params=new URLSearchParams({...query,after:connection.pageInfo.endCursor});return <nav className="pagination" aria-label="Pagination"><a className="button" href={base+'?'+params.toString()}>More stories ↗</a><a href={base+(Object.keys(query).length?'?'+new URLSearchParams(query):'')}>Back to first page</a></nav>;}
export function Heading({eyebrow='The journal',title,description}){return <header className="page-heading"><span className="eyebrow accent">{eyebrow}</span><h1>{text(title)}</h1>{description&&<p>{text(description)}</p>}</header>;}
export function RichText({value}) {return <div className="prose" dangerouslySetInnerHTML={{__html:html(value)}}/>;}
export function SeriesFeature({series}){if(!series?.frontendUrl)return null;return <section className="feature-series"><div className="series-copy"><span className="eyebrow">The Arcwell series {series.arcwellEditionLabel?' / '+series.arcwellEditionLabel:''}</span><h2>{text(series.title)}</h2><p>{text(series.excerpt)}</p><a className="text-link" href={'/series/'+series.slug+'/'}>Explore the series ↗</a></div><div className="series-art" aria-hidden="true"><span className="issue">A FIELD GUIDE TO THE EVERYDAY</span><div className="orbit"/><strong>{series.arcwellArtLabel||'Observe.'}</strong><span className="eyebrow">{series.publishedPostCount} stories · One new perspective</span></div></section>;}
export function Homepage({home,posts,site}) {
 const hero=home?.hero?.frontendUrl?home.hero:posts[0];const picks=(home?.editorsPicks||[]).filter(p=>p.frontendUrl&&p.databaseId!==hero?.databaseId);const edit=picks.length?picks:posts.filter(p=>p.databaseId!==hero?.databaseId).slice(0,3);const topic=home?.featuredTopic;const about=home?.aboutPage;
 return <><section className="intro"><h1>{home?.heading||'A wider view.'}<br/><em>{home?.emphasis||'A deeper read.'}</em></h1><p>{home?.intro||site.arcwell.tagline||'Ideas, places, and people shaping a more considered world. Take a moment. Stay curious.'}</p></section>{hero?<section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><span className="eyebrow accent">The cover story</span><h2 id="hero-title"><a href={articlePath(hero)}>{text(hero.title)}</a></h2><p>{text(hero.excerpt)}</p><Byline post={hero}/><a className="text-link" href={articlePath(hero)}>Step inside the story ↗</a></div><a className="hero-photo" href={articlePath(hero)}><Picture image={postImage(hero)} priority/>{home?.heroOverlay&&<span className="photo-label">{home.heroOverlay}</span>}<span className="round-arrow" aria-hidden="true">↗</span></a></section>:<Empty title="A new perspective is on its way."/>}{edit.length>0&&<section className="section"><div className="section-head"><h2>The considered edit</h2><a className="text-link" href="/journal/">{picks.length?"Editor's picks":"Explore stories"} ↗</a></div><Cards posts={edit}/></section>}<SeriesFeature series={home?.featuredSeries}/><section className={'section '+(topic?'latest-layout':'')}><div><div className="section-head"><h2>Fresh from the journal</h2><a className="text-link" href="/journal/">View all stories ↗</a></div>{posts.slice(0,5).map((p,i)=><article key={p.databaseId} className="story-row"><span className="number">{String(i+1).padStart(2,'0')}</span><div><Category post={p}/><h3><a href={articlePath(p)}>{text(p.title)}</a></h3><Byline post={p}/></div><a href={articlePath(p)}><Picture image={postImage(p)}/></a></article>)}</div>{topic&&<aside className="topic-panel"><span className="eyebrow accent">In focus / {text(topic.name)}</span><h3>{text(topic.arcwellPromoHeading||topic.name)}</h3><p>{text(topic.description)}</p><Picture image={topic.arcwellImage}/><a className="text-link" href={'/topics/'+topic.slug+'/'}>Explore {text(topic.name)} ↗</a></aside>}</section><section className="manifesto"><h2>{home?.manifestoHeading||'For those who look a little closer.'}<br/><em>{home?.manifestoEmphasis||'And wonder a little longer.'}</em></h2>{about?.frontendUrl&&<a className="button" href={route(about.frontendUrl)}>Meet Arcwell ↗</a>}</section></>;
}
export function Article({post}){const image=post.featuredImage?.node;const author=post.author?.node;const credit=image?.arcwellCredit;return <><header className="article-heading"><Category post={post}/><h1>{text(post.title)}</h1><p className="dek">{text(post.excerpt)}</p><Byline post={post}/>{post.date&&<p className="meta">{new Date(post.date).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}</p>}</header>{image&&<figure className="article-image"><Picture image={image} priority/>{(image.caption||credit?.photographer)&&<figcaption>{text(image.caption)} {credit?.photographer&&<>Photography: {credit.sourceUrl&&safeUrl(credit.sourceUrl)?<a href={safeUrl(credit.sourceUrl)} rel="noopener noreferrer">{credit.photographer}</a>:credit.photographer}</>}{credit?.licenseLabel&&<> · {credit.licenseUrl&&safeUrl(credit.licenseUrl)?<a href={safeUrl(credit.licenseUrl)}>{credit.licenseLabel}</a>:credit.licenseLabel}</>}</figcaption>}</figure>}<div className="article-layout"><aside className="article-aside"><span className="eyebrow">The journal</span><p>A story worth slowing down for.</p><Share/>{publicNodes(post.arcwellSeries).map(s=><p key={s.slug}><a href={'/series/'+s.slug+'/'}>{text(s.title)} ↗</a></p>)}</aside><div><RichText value={post.content}/>{author&&<div className="author-box"><span className="initials">{text(author.name).split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><a href={'/authors/'+author.slug+'/'}><strong>{text(author.name)}</strong></a><p>{text(author.description||author.arcwellSpecialty)}</p></div></div>}</div></div></>;}
