"""Generate the static design-review pages. Run: python3 HTML/build.py."""
from pathlib import Path
from html import escape
import json
ROOT = Path(__file__).parent
stories = [
 {'slug':'spaces-to-slow-down','title':'The spaces that teach us to slow down','category':'Design','image':'architecture','alt':'Angular modern home with illuminated windows against a pale evening sky','author':'Alex Morgan','time':'8 min read','date':'Sep 14, 2026','description':'Beyond the noise of modern life, a quieter kind of architecture is making room for what matters.','section':'Architecture'},
 {'slug':'less-but-better','title':'Less, but better. The objects we choose to keep.','category':'Culture','image':'chair','alt':'White molded chair with wooden legs in a minimal room','author':'Jamie Chen','time':'5 min read','date':'Sep 12, 2026','description':'A considered life starts with the everyday things we surround ourselves with.','section':'Objects & rituals'},
 {'slug':'forest-listening','title':'What happens when we listen to the forest?','category':'Nature','image':'forest','alt':'Evergreen forest disappearing into soft mountain mist','author':'Alex Morgan','time':'7 min read','date':'Sep 11, 2026','description':'A field note on attention, stillness, and the world just beyond our screens.','section':'The natural world'},
 {'slug':'cities-human-scale','title':'Building cities at a more human scale','category':'Ideas','image':'building','alt':'Geometric white and turquoise building seen from below against blue sky','author':'Sam Rivera','time':'6 min read','date':'Sep 10, 2026','description':'The future of our cities might begin with a very simple question: who are they for?','section':'Future of living'},
 {'slug':'taking-long-way','title':'The quiet joy of taking the long way home','category':'Nature','image':'landscape','alt':'Small cabin below an autumn-colored mountain and blue sky','author':'Jamie Chen','time':'4 min read','date':'Sep 9, 2026','description':'On wandering without an itinerary, and finding a different sense of time.','section':'Field notes'},
 {'slug':'objects-with-stories','title':'Some objects have more stories to tell','category':'Culture','image':'interior','alt':'Vintage tufted armchair against a warm wooden wall','author':'Alex Morgan','time':'5 min read','date':'Sep 8, 2026','description':'Why the things that age with us can be the things we value most.','section':'Objects & rituals'},
]
mark='<svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M20 2v36M2 20h36M7.3 7.3l25.4 25.4M7.3 32.7 32.7 7.3" stroke="currentColor" stroke-width="5"/></svg>'
search_icon='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor" stroke-width="1.6"/><path d="m16 16 5 5" stroke="currentColor" stroke-width="1.6"/></svg>'
menu_icon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 7h18M3 12h18M3 17h18" stroke="currentColor" stroke-width="1.5"/></svg>'
def url(s): return 'article.html?story='+s['slug']
def img(s, eager=False): return f'<img src="assets/images/{s["image"]}.jpg" alt="{s["alt"]}" width="960" height="640" '+('fetchpriority="high"' if eager else 'loading="lazy"')+'>'
def meta(s): return f'<div class="meta"><a href="author.html?name={s["author"].replace(" ","%20")}">{s["author"]}</a><span>·</span><span>{s["time"]}</span></div>'
def card(s): return f'<article class="card" data-category="{s["category"]}"><a class="image-link" href="{url(s)}">{img(s)}</a><a class="eyebrow accent" href="archive.html?category={s["category"]}">{s["category"]} <span>—</span> {s["section"]}</a><h3><a href="{url(s)}">{s["title"]}</a></h3>{meta(s)}</article>'
def row(s,n): return f'<article class="story-row"><span class="number">0{n}</span><div><a class="eyebrow accent" href="archive.html?category={s["category"]}">{s["category"]}</a><h3><a href="{url(s)}">{s["title"]}</a></h3>{meta(s)}</div><a href="{url(s)}">{img(s)}</a></article>'
def section_head(title,link='archive.html',label='View all stories'): return f'<div class="section-head"><h2>{title}</h2><a class="text-link" href="{link}">{label}<span aria-hidden="true">↗</span></a></div>'
def layout(name,title,body,active=''):
 nav=''.join(f'<a href="{href}"'+(' aria-current="page"' if active==label else '')+f'>{label}</a>' for label,href in [('The journal','archive.html'),('Topics','topics.html'),('Series','series.html'),('About us','page.html')])
 text=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Arcwell — An independent journal of design, culture, nature, and new perspectives."><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#f7f5ef"><title>{title} — Arcwell</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="assets/css/styles.css"><script src="assets/js/stories.js" defer></script><script src="assets/js/main.js" defer></script></head>
<body data-page="{name}"><a class="skip" href="#main">Skip to content</a><div class="wrap"><div class="topline"><span>An independent journal for the curious</span><span class="live"><span class="dot"></span> Fresh perspectives, thoughtfully told</span><span>Est. 2026 · Issue 01</span></div><header class="header"><a class="brand" href="index.html" aria-label="Arcwell home">{mark}arcwell</a><nav class="nav" id="main-nav" aria-label="Main navigation">{nav}</nav><div class="header-actions"><a class="icon" href="search.html" aria-label="Search the journal">{search_icon}</a><button class="icon menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="main-nav">{menu_icon}</button></div></header></div>
<main id="main" class="wrap">{body}</main>
<footer><div class="wrap"><div class="footer-top"><div><a class="brand" href="index.html">{mark}arcwell</a><p>A wider view of the world.<br>Stories worth slowing down for.</p></div><div class="footer-links"><div><span class="eyebrow">Explore</span><a href="archive.html">The journal</a><a href="topics.html">Our topics</a><a href="series.html">Editorial series</a></div><div><span class="eyebrow">Arcwell</span><a href="page.html">About the journal</a><a href="author.html">Our contributors</a><a href="credits.html">Photography & credits</a></div></div></div><div class="footer-bottom"><span>© 2026 Arcwell. Made for a more curious world.</span><span>Design prototype · Sample editorial content<br><a href="blocks.html">Block library</a> · <a href="404.html">404 preview</a></span></div></div></footer></body></html>'''
 (ROOT/(name+'.html')).write_text(text)
s=stories[0]
layout('index','A wider view. A deeper read.',f'''<section class="intro"><h1>A wider view.<br><em>A deeper read.</em></h1><p>Ideas, places, and people shaping a more considered world. Take a moment. Stay curious.</p></section><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><span class="eyebrow accent"><span class="dot"></span> The cover story <span> / </span> Design</span><h2 id="hero-title"><a href="{url(s)}">{s['title']}</a></h2><p>{s['description']}</p>{meta(s)}<a class="text-link" href="{url(s)}">Step inside the story <span aria-hidden="true">↗</span></a></div><a class="hero-photo" href="{url(s)}">{img(s,True)}<span class="photo-label">Space to think. Room to breathe.</span><span class="round-arrow" aria-hidden="true">↗</span></a></section><section class="section">{section_head('The considered edit <span>01—03</span>',label="Editor's picks")}<div class="cards">{''.join(card(x) for x in stories[1:4])}</div></section><section class="feature-series" aria-labelledby="series-title"><div class="series-copy"><span class="eyebrow">The Arcwell series / No. 01</span><h2 id="series-title">The art of<br>paying attention.</h2><p>Small observations. Unexpected connections. A collection on finding more in the everyday.</p><a class="text-link" href="series.html">Explore the series <span aria-hidden="true">↗</span></a></div><div class="series-art" aria-hidden="true"><span class="issue">A FIELD GUIDE TO THE EVERYDAY</span><div class="orbit"></div><strong>Observe.</strong><span class="eyebrow">4 stories · One new perspective</span></div></section><section class="section latest-layout"><div>{section_head('Fresh from the journal')} {''.join(row(x,i+1) for i,x in enumerate(stories[3:]))}</div><aside class="topic-panel"><span class="eyebrow accent">In focus / Nature</span><h3>A little closer<br>to the wild.</h3><p>Step outside the familiar. Explore stories about our relationship with the natural world.</p>{img(stories[2])}<a class="text-link" href="archive.html?category=Nature">Explore nature <span aria-hidden="true">↗</span></a></aside></section><section class="manifesto"><h2>For those who look a little closer.<br><em>And wonder a little longer.</em></h2><a class="button" href="page.html">Meet Arcwell <span aria-hidden="true">↗</span></a></section>''')
layout('archive','The journal',f'''<header class="page-heading"><span class="eyebrow accent">The journal / All perspectives</span><h1 id="archive-title">Stay curious.</h1><p id="archive-description">Fresh thinking, thoughtful places, and stories that stay with you. Find your next good read.</p></header><nav class="filters" aria-label="Filter stories">{''.join(f'<a class="filter" data-filter="{c}" href="archive.html'+('' if c=='All stories' else '?category='+c)+f'">{c}</a>' for c in ['All stories','Design','Culture','Nature','Ideas'])}</nav><p class="results-count" id="archive-count" aria-live="polite">6 stories to explore</p><section class="cards archive-grid" id="archive-results" aria-label="Stories">{''.join(card(x) for x in stories)}</section><div class="archive-end"><p class="results-count">You’re all caught up. A new perspective is always on its way.</p><a class="text-link" href="topics.html">Explore our topics <span>↗</span></a></div>''','The journal')
layout('topics','Our topics',f'''<header class="page-heading"><span class="eyebrow accent">Follow your curiosity</span><h1>Different lenses.<br>One shared world.</h1><p>Start with what draws you in. See where it takes you.</p></header><section class="cards archive-grid section">{''.join(f'<article class="card"><a class="image-link" href="archive.html?category={c}">{img(stories[i])}</a><span class="eyebrow accent">0{n+1} / Explore a perspective</span><h2 style="font-size:42px;margin:15px 0"><a href="archive.html?category={c}">{c} ↗</a></h2><p class="description">{d}</p></article>' for n,(c,i,d) in enumerate([('Design',0,'Spaces and objects that shape the way we live.'),('Culture',1,'The rituals, ideas, and stories we share.'),('Nature',2,'A closer connection to the world outside.'),('Ideas',3,'New ways to think about what comes next.')]))}</section>''','Topics')
article_body='''<p class="lead">There is a moment, just before evening, when a room begins to change. The light moves across a wall. Familiar objects take on a different weight. For a few minutes, the space asks nothing of us except that we notice it.</p><p>We tend to talk about architecture in terms of what it adds: more floor space, more light, more possibilities. But some of the most inviting places begin with another question. What can a space give us permission to set down?</p><h2 id="room">Making room for less</h2><p>A considered home does not have to be empty. It has to leave enough room for living. A chair placed beside a window, a table that gathers the afternoon light, a doorway that frames a tree: these are small choices with a lasting effect.</p><p>Instead of filling every corner, we can begin by noticing how we move through a place. Where do we pause? Where do we feel at ease? The answers are often quieter than the objects around them.</p><blockquote>“A good space doesn’t demand your attention. It gives it back to you.”</blockquote><h2 id="everyday">The everyday, reconsidered</h2><p>There is no single aesthetic for a slower life. A room can be colorful, busy, and full of history, yet still offer a sense of belonging. What matters is the relationship between the things we keep and the lives we want to lead.</p><figure><img src="assets/images/chair.jpg" alt="A simple white chair with wooden legs beside a pale wall" width="960" height="1463" loading="lazy"><figcaption>A familiar object, given space. Photograph by Matt Bango / StockSnap.</figcaption></figure><p>Try looking at one small corner of your home without thinking about how it photographs. Think instead about how it feels at the beginning of the day. Sometimes a modest change is enough to make the ordinary feel newly welcoming.</p><h2 id="attention">An invitation to notice</h2><p>Perhaps the real promise of thoughtful design is not a more impressive room. It is a better relationship with the time we spend inside it. The space remains familiar. Our attention changes.</p><p>And that is a good place to begin.</p>'''
layout('article',s['title'],f'''<header class="article-heading"><a class="eyebrow accent" id="article-category" href="archive.html?category=Design">Design / Architecture</a><h1 id="article-title">{s['title']}</h1><p class="dek" id="article-description">{s['description']}</p><div id="article-meta">{meta(s)}</div><p class="meta" id="article-date" style="margin-top:12px">September 14, 2026</p></header><figure class="article-image"><div id="article-photo">{img(s,True)}</div><figcaption id="article-caption">Photograph by Matt Bango / StockSnap</figcaption></figure><div class="article-layout"><aside class="article-aside"><span class="eyebrow">In this story</span><nav id="contents" aria-label="Article contents"><a href="#room">Making room for less</a><a href="#everyday">The everyday, reconsidered</a><a href="#attention">An invitation to notice</a></nav><hr><button class="button" id="share-article">Copy story link ↗</button><p id="share-status" class="status" role="status"></p><a href="series.html">Part of: The art of paying attention →</a></aside><article class="prose"><div id="article-body">{article_body}</div><div class="author-box"><span class="initials" id="byline-initials">AM</span><div><strong><a href="author.html" id="byline-name">Alex Morgan</a></strong><p id="byline-bio">Writing about design, everyday rituals, and a more considered way of living.</p></div></div></article></div><section class="section" style="border-top:1px solid var(--line)">{section_head('Keep exploring')}<div class="cards">{''.join(card(x) for x in stories[1:4])}</div></section>''','The journal')
layout('author','Alex Morgan',f'''<header class="page-heading author-hero"><div><span class="eyebrow accent">The voices behind the journal</span><h1 id="author-name">Alex Morgan</h1><p id="author-bio">A writer exploring the relationship between the places we inhabit and the lives we lead. Interested in thoughtful design, quiet rituals, and the occasional long walk.</p><p class="eyebrow" style="margin-top:25px">Contributor / Design & everyday life</p></div><div class="author-mark" aria-hidden="true" id="author-initials">AM</div></header><section class="section">{section_head('Stories by Alex',label='The full journal')}<div class="cards" id="author-stories">{''.join(card(x) for x in stories if x['author']=='Alex Morgan')}</div></section>''')
layout('series','The art of paying attention',f'''<header class="page-heading"><span class="eyebrow accent">Editorial series / No. 01</span><h1>The art of<br><em>paying attention.</em></h1><p>A field guide to the everyday. Four stories about slowing down, looking closer, and finding something extraordinary in what is already here.</p></header><section class="feature-series"><div class="series-copy"><span class="eyebrow">A collection, thoughtfully connected</span><h2>Less scrolling.<br>More noticing.</h2><p>From the rooms we live in to the paths we follow, a new perspective begins with a little attention.</p><a class="text-link" href="{url(stories[0])}">Start with chapter one <span>↗</span></a></div><div class="series-art" aria-hidden="true"><span class="issue">THE ARCWELL SERIES</span><div class="orbit"></div><strong>Observe.</strong><span class="eyebrow">01 / A field guide to the everyday</span></div></section><section class="section"><div class="section-head"><h2>Inside the series</h2><span class="eyebrow">4 stories / 24 minutes</span></div>{''.join(row(stories[i],n+1) for n,i in enumerate([0,1,2,4]))}</section>''','Series')
layout('search','Search the journal',f'''<header class="page-heading"><span class="eyebrow accent">Follow a thought</span><h1>What’s on your mind?</h1><p>Find a story, explore an idea, or discover something unexpected.</p></header><form class="search-form" action="search.html" method="get" role="search"><label class="sr-only" for="query">Search stories</label><input type="search" id="query" name="q" placeholder="Try “design” or “nature”" maxlength="150"><button class="button solid" type="submit">Search ↗</button></form><p id="search-count" class="results-count" role="status">A few stories to get you started</p><section id="search-results" class="cards archive-grid section" aria-label="Search results">{''.join(card(x) for x in stories[:3])}</section>''')
layout('page','About the journal',f'''<section class="about-hero"><div><span class="eyebrow accent">Hello, we’re Arcwell.</span><h1>A little more<br><em>perspective.</em></h1><p>We believe good stories make the world feel bigger. And, somehow, bring us a little closer together.</p><p>Arcwell is an independent journal about design, culture, nature, and the ideas connecting them. A place for thoughtful voices and unhurried reading.</p><a class="text-link" style="margin-top:30px" href="archive.html">Find your first story <span>↗</span></a></div>{img(stories[2],True)}</section><section class="manifesto"><h2>Curiosity is a practice.<br><em>Make a little room for it.</em></h2><span class="eyebrow">Our point of view</span></section><section class="about-values"><div><span class="eyebrow accent">01 / Thoughtful</span><h2>Depth over noise.</h2><p>We give ideas the time and space they deserve. Every story begins with a question worth asking.</p></div><div><span class="eyebrow accent">02 / Open</span><h2>A wider lens.</h2><p>Interesting things happen where perspectives meet. We look for connections across disciplines and experiences.</p></div><div><span class="eyebrow accent">03 / Human</span><h2>Close to everyday life.</h2><p>Good stories stay with you after you close the page. They change how you see a familiar place or an ordinary moment.</p></div></section>''','About us')
layout('404','A small detour','''<section class="not-found"><span class="eyebrow" style="justify-content:center">A small detour</span><p class="code">404</p><h1>This story hasn’t found its way here.</h1><p>The page may have moved, or the address might be a little off.<br>There’s still plenty to discover.</p><a class="button solid" href="index.html">Back to the journal ↗</a><a class="button" href="search.html">Search for a story</a></section>''')
layout('blocks','The editorial block library','''<header class="page-heading"><span class="eyebrow accent">Design reference / Gutenberg</span><h1>The building blocks.</h1><p>A visual reference for the supported editorial blocks. These static examples guide the production rendering.</p></header><div class="block-grid"><aside class="article-aside"><span class="eyebrow">In this library</span><nav aria-label="Block library"><a href="#type">Type & lists</a><a href="#media">Images & gallery</a><a href="#quote">Quote & code</a><a href="#table">Table & buttons</a><a href="#layout">Columns, group & cover</a><a href="#embed">Embed</a></nav></aside><div class="prose"><section class="block-section" id="type"><span class="eyebrow accent">01 / Paragraph, heading, list & separator</span><h2>Good stories need room to breathe.</h2><p>A clear typographic rhythm makes space for the ideas on the page. This is the standard paragraph style for long-form editorial content.</p><h3>A closer look</h3><ul><li>Start with a question worth exploring.</li><li>Follow the details that surprise you.</li><li>Leave room for a different perspective.</li></ul><ol><li>Observe the familiar.</li><li>Consider a new angle.</li></ol><hr></section><section class="block-section" id="media"><span class="eyebrow accent">02 / Image & gallery</span><figure><img src="assets/images/forest.jpg" alt="A mist-covered evergreen forest" width="960" height="640" loading="lazy"><figcaption>Quiet moments in the natural world. Redd Angelo / StockSnap.</figcaption></figure><div class="gallery"><img src="assets/images/chair.jpg" alt="Modern white chair with wood legs" width="960" height="1463" loading="lazy"><img src="assets/images/interior.jpg" alt="Vintage chair in a wood-paneled room" width="960" height="1200" loading="lazy"></div></section><section class="block-section" id="quote"><span class="eyebrow accent">03 / Quote & code</span><blockquote>“Attention is the beginning of a different kind of discovery.”</blockquote><pre><code>const journal = {
  perspective: 'open',
  pace: 'considered',
  curiosity: true
};</code></pre></section><section class="block-section" id="table"><span class="eyebrow accent">04 / Table & buttons</span><div class="table-wrap"><table><caption>Our editorial perspectives</caption><thead><tr><th scope="col">Perspective</th><th scope="col">What we explore</th></tr></thead><tbody><tr><th scope="row">Design</th><td>Spaces, objects, and everyday life</td></tr><tr><th scope="row">Nature</th><td>Our connection to the world outside</td></tr></tbody></table></div><p><a href="archive.html" class="button solid">Explore the journal ↗</a></p></section><section class="block-section" id="layout"><span class="eyebrow accent">05 / Columns, group & cover</span><div class="columns"><div><h3>One perspective.</h3><p>A place to begin a thought and follow it somewhere new.</p></div><div><h3>Another possibility.</h3><p>Two related ideas, side by side, with room for each to breathe.</p></div></div><div class="group"><h3>A connected thought.</h3><p>A grouped collection of content with a shared background.</p></div><div class="cover"><h3>A little closer to the wild.</h3></div></section><section class="block-section" id="embed"><span class="eyebrow accent">06 / Embed</span><div class="embed-demo"><p>External media</p><p>Embedded video or audio appears here after consent.</p><button class="button" id="embed-preview">Preview embed state ↗</button><p id="embed-status" role="status" class="status"></p></div></section></div></div>''')
credits=[('architecture','modern-design-KQA30E4YCM','Matt Bango'),('chair','interior-chair-DQGQZHMELB','Matt Bango'),('forest','forest-mountain-MPT8URNNRA','Redd Angelo'),('building','modern-architecture-2NXVMGDETI','Tom Hill'),('landscape','mountain-forest-DQPDTHTCJS','Nathan Anderson'),('interior','interior-chair-E3PW2UR6AE','Matt Bango')]
layout('credits','Photography & credits','''<header class="page-heading"><span class="eyebrow accent">With appreciation</span><h1>Behind the images.</h1><p>Photography gives a story another dimension. These images are sourced from StockSnap, with CC0 licensing indicated on their source pages.</p></header><section class="cards archive-grid section">'''+''.join(f'<article class="card"><img src="assets/images/{file}.jpg" alt="{next(s["alt"] for s in stories if s["image"]==file)}" width="960" height="640" loading="lazy"><h2 style="font-size:27px;margin:20px 0">{author}</h2><a class="text-link" href="https://stocksnap.io/photo/{source}">View original photograph ↗</a></article>' for file,source,author in credits)+'''</section><section class="manifesto"><div><h2>Type with character.</h2><p>Manrope and Newsreader, served by Google Fonts.</p></div><a class="text-link" href="https://stocksnap.io/license">StockSnap license ↗</a></section>''')
(ROOT/'assets/js/stories.js').write_text('window.ARCWELL_STORIES = '+json.dumps(stories,ensure_ascii=False)+';\n')
(ROOT/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="6" fill="#f7f5ef"/><path d="M20 5v30M5 20h30M9 9l22 22M9 31 31 9" stroke="#b83c21" stroke-width="4"/></svg>')
print('Generated 11 HTML pages and shared story fixtures.')
