import {notFound} from 'next/navigation';
import {getSite,getHome,getPosts,getPost,getPage,getTopics,getTopic,getTaxonomy,getSeriesList,getSeries,getAuthor} from '../../lib/wp.mjs';
import {text,route,publicNodes,origin} from '../../lib/content.mjs';
import {Homepage,Article,Heading,Cards,Pagination,Picture,RichText,Empty,SeriesFeature} from '../../components/Editorial';
import {previewForPath} from '../../lib/preview.mjs';
const scalar=value=>typeof value==='string'?value:null;
export async function generateMetadata({params}){const {segments=[]}=await params;const path='/'+segments.join('/')+(segments.length?'/':'');const preview=await previewForPath(path);if(preview)return {title:'Preview — '+text(preview.node.title),robots:{index:false,follow:false}};let node;if(segments[0]==='articles'&&segments.length===2){node=await getPost(segments[1]);if(!node?.frontendUrl)notFound();}return {title:node?text(node.title):segments.length?text(segments[0].replace(/-/g,' ')):'A wider view. A deeper read.',description:node?text(node.excerpt).slice(0,160):undefined,alternates:{canonical:origin()+path},openGraph:node?{title:text(node.title),description:text(node.excerpt).slice(0,160),type:'article',images:node.featuredImage?.node?.sourceUrl?[node.featuredImage.node.sourceUrl]:[]}:undefined};}
export default async function Page({params,searchParams}) {
 const {segments=[]}=await params;const search=await searchParams;const after=scalar(search.after);const path='/'+segments.join('/')+(segments.length?'/':'');
 const preview=await previewForPath(path);
 let content;
 if(preview){const {node,claims}=preview;content=claims.entityType==='post'?<Article post={node}/>:claims.entityType==='page'&&path==='/'?<Homepage home={node.arcwellHomepage} posts={publicNodes((await getHome()).posts)} site={await getSite()}/>:<><Heading title={node.title} eyebrow="Preview"/><div className="page-content"><RichText value={node.content}/></div>{node.arcwellPosts&&<Cards posts={publicNodes(node.arcwellPosts)}/>}</>;}
 else if(!segments.length){const [data,site]=await Promise.all([getHome(),getSite()]);content=<Homepage home={data.arcwellHomepage} posts={publicNodes(data.posts)} site={site}/>;}
 else if(segments[0]==='articles'&&segments.length===2){const post=await getPost(segments[1]);if(!post?.frontendUrl)notFound();content=<Article post={post}/>;}
 else if(segments[0]==='journal'&&segments.length===1){const [posts,site]=await Promise.all([getPosts({after}),getSite()]);content=<><Heading title="The journal." description="Ideas, observations, and stories worth slowing down for."/><nav className="filters" aria-label="Categories"><a href="/journal/" aria-current="page">All stories</a>{site.categories.nodes.filter(t=>t.count>0).map(t=><a key={t.slug} href={'/category/'+t.slug+'/'}>{text(t.name)}</a>)}</nav><Cards posts={publicNodes(posts)}/><Pagination connection={posts} base={path}/></>;}
 else if(segments[0]==='search'&&segments.length===1){const q=(scalar(search.q)||'').trim().slice(0,150);const posts=q?await getPosts({after,search:q}):null;content=<><Heading title="Follow your curiosity." eyebrow="Search the journal"/><form className="search-form" action="/search/"><label className="sr-only" htmlFor="query">Search stories</label><input id="query" name="q" type="search" defaultValue={q} maxLength={150} placeholder="What are you curious about?"/><button className="button" type="submit">Search ↗</button></form>{posts?<section className="section"><p>Stories matching “{q}”</p><Cards posts={publicNodes(posts)}/><Pagination connection={posts} base={path} query={{q}}/></section>:<p>Search for a subject, place, or idea.</p>}</>;}
 else if(segments[0]==='topics'&&segments.length===1){const topics=await getTopics(after);content=<><Heading title="A world of perspectives." eyebrow="Follow your curiosity"/>{topics.nodes.length?<section className="cards section">{topics.nodes.map(t=><article className="card" key={t.slug}><a className="image-link" href={'/topics/'+t.slug+'/'}><Picture image={t.arcwellImage}/></a><h3><a href={'/topics/'+t.slug+'/'}>{text(t.name)}</a></h3><p>{text(t.description)}</p></article>)}</section>:<Empty title="New perspectives are taking shape."/>}<Pagination connection={topics} base={path}/></>;}
 else if(segments[0]==='topics'&&segments.length===2){const topic=await getTopic(segments[1],after);if(!topic)notFound();content=<><Heading title={topic.name} description={topic.description}/><Cards posts={publicNodes(topic.posts)}/><Pagination connection={topic.posts} base={path}/></>;}
 else if(['category','tags'].includes(segments[0])&&segments.length===2){const taxonomy=await getTaxonomy(segments[0]==='category'?'category':'tag',segments[1]);if(!taxonomy)notFound();const posts=await getPosts({after,...(segments[0]==='category'?{categoryName:segments[1]}:{tag:segments[1]})});content=<><Heading title={taxonomy.name} description={taxonomy.description}/><Cards posts={publicNodes(posts)}/><Pagination connection={posts} base={path}/></>;}
 else if(segments[0]==='series'&&segments.length===1){const series=await getSeriesList(after);content=<><Heading title="Stories in good company." eyebrow="Editorial series"/>{publicNodes(series).length?publicNodes(series).map(s=><SeriesFeature key={s.databaseId} series={s}/>):<Empty title="Our next collection is on its way."/>}<Pagination connection={series} base={path}/></>;}
 else if(segments[0]==='series'&&segments.length===2){const series=await getSeries(segments[1],after);if(!series?.frontendUrl)notFound();content=<><Heading title={series.title} eyebrow={series.arcwellEditionLabel||'Editorial series'} description={series.excerpt}/>{series.content&&<div className="page-content"><RichText value={series.content}/></div>}<Cards posts={publicNodes(series.arcwellPosts)}/><Pagination connection={series.arcwellPosts} base={path}/></>;}
 else if(segments[0]==='authors'&&segments.length===2){const author=await getAuthor(segments[1]);if(!author?.frontendUrl)notFound();const posts=await getPosts({after,authorName:segments[1]});content=<><Heading title={author.name} eyebrow={author.arcwellSpecialty||'Contributor'} description={author.description}/><Cards posts={publicNodes(posts)}/><Pagination connection={posts} base={path}/></>;}
 else {const page=await getPage(path);if(!page?.frontendUrl)notFound();content=<><Heading title={page.title} eyebrow={page.arcwellPresentation?.template==='about'?'Meet Arcwell':'The journal'}/>{page.featuredImage?.node&&<figure className="article-image"><Picture image={page.featuredImage.node} priority/></figure>}<div className="page-content"><RichText value={page.content}/></div>{page.arcwellPresentation?.values?.length>0&&<section className="about-values">{page.arcwellPresentation.values.map((v,i)=><div key={i}><span className="eyebrow accent">{String(i+1).padStart(2,'0')}</span><h2>{v.heading}</h2><p>{v.body}</p></div>)}</section>}</>;}
 return <>{preview&&<div className="preview-banner">Preview · visible only in this preview session<a href="/api/arcwell/preview/exit">Exit preview</a></div>}<main id="main" className="wrap">{content}</main></>;
}
